name: DeathPenalties
load: POSTWORLD
description: DeathPenalties is a plugin from the WaffleProject's plugins collection that is designed to prevent players to abuse from death advantages and even penalize them !
main: be.waslet.dp.main.DeathPenalties
version: Release-1.3
authors: [Whawhatausore]
website: http://www.waffleproject.com/
database: false
softdepend: [Multiverse-Core, Vault]
permissions:
  dp.ignore:
    description: This permission allows to ignore death penalties
    default: op
  dp.commands.info:
    description: This permission allows the usage of info level commands
    default: op
  dp.commands.edit:
    description: This permission allows the usage of editing level commands
    default: op
  dp.commands.*:
    description: This permission allows the usage of all commands
    default: op
    children:
      dp.commands.info: true
      dp.commands.toggle: true
  dp.*:
    description: This permission allow you to ignore death penalties and allows the usage of all commands
    default: op
    children:
      dp.ignore: true
      dp.commands.*: true
commands:
  dpstate:
    description: Shows death penalties world(s) values
    usage: /dpstate <world_name> (You can use the word "all" to see every worlds state)
    permission: dp.commands.info
  dpedit:
    description: Edit death penalties world(s) values
    usage: /dpedit <world_name> <option_name> <option_value> (You can use the word "all" to edit every worlds)
    permission: dp.commands.edit